# App
application:
  name: isp
  image: levigoldman/identity
  replicaCount: 1
  port: 8000
  domain: rnd-identityserver-dev.godeltech.com


# Redis
redis:
  image: redis
  replicaCount: 1
  name: redis
  port: 6379


# Parameters for the secret containing ContainerRegistry's credentials
imagePullSecret:
  server: https://index.docker.io/v1
  username: levigoldman
  password: PUSH2023levi


# Application Service properties
service:
  port: 8000
  targetPort: 8000
  type: ClusterIP
