apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.application.name  }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name  }}
    spec:
      containers:
      - name: {{ .Values.application.name  }}
        image: isp
        imagePullPolicy: Never
        resources: {{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.application.port  }}
          protocol: TCP
