apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name  }}
spec:
  replicas: {{ .Values.application.replicaCount  }}
  selector:
    matchLabels:
      app: {{ .Values.application.name  }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name  }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.application.name  }}
      containers:
      - name: isp
        image: {{ .Values.application.image  }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.application.port  }}
          protocol: TCP
