apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.application.name  }}
#  namespace: {{ .Values.application.namespace  }}
  annotations:
    kubernetes.io/ingress.class: nginx
#    ingress.kubernetes.io/ssl-redirect: "true"
#    kubernetes.io/ingress.allow-http: 'false'
#    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.application.name }}
              servicePort: {{ .Values.service.port }}
