apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name  }}
  namespace: {{ .Values.application.namespace  }}
spec:
  replicas: {{ .Values.application.replicaCount  }}
  selector:
    matchLabels:
      app: {{ .Values.application.name  }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name  }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.application.name | lower }}-cr
      containers:
      - name: {{ .Values.application.name  }}
        image: {{ .Values.application.image  }}
        imagePullPolicy: Always
        env:
          - name: ENVIRONMENT_NAME
            value: {{ .Values.environment_name }}
        ports:
        - containerPort: {{ .Values.application.port  }}
          protocol: TCP
