include:
  - project: 'gte-internal/ci-cd/essential'
    ref: "0.1.4"
    file: '/ci-templates/.deployment.yml'
  - project: 'gte-internal/ci-cd/essential'
    ref: "0.1.2"
    file: '/ci-templates/.container.yml'
  - project: 'gte-internal/ci-cd/e2e-testing'
    ref: "0.1"
    file: '/ci-templates/.e2e-tests.yml'
  - project: 'gte-internal/ci-cd/deployment-with-pact'
    ref: "0.1"
    file: '/ci-templates/.deployment-with-pact.yml'


stages:
  - container
  - build
  - deploy-to-dev


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  SERVICE_NAME: identity-server-poc
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_IMAGE_PATH: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${SERVICE_NAME}-${CI_PIPELINE_ID}


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/


#################
# CONTAINER
#################

container:docker-build:
  extends: .docker-build-artifact
  rules:
    - when: always


#################
# BUILD-AND-TEST
#################

build-and-test:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker run -d --name identity-server-provider -p 8000:8000 --env ENV_FOR_DYNACONF=pipeline -v /var/run/docker.sock:/var/run/docker.sock ${DOCKER_IMAGE_PATH}
    - docker exec -i identity-server-provider sh -c "pytest --cov=src"
    - echo ${CI_REGISTRY}
    - echo ${$CI_REGISTRY_USER}
    - echo ${$CI_JOB_TOKEN}
    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_HASH}
    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:${SERVICE_NAME}-${CI_PIPELINE_ID}
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    - when: always


#################
# DEPLOY-TO-DEV
#################
#
#deploy-to-dev:
##  extends: .deploy-to-dev-ext
#  stage: deploy-to-dev
##  variables:
##    ENV_FOR_DYNACONF: development
##    SERVICE: "${SERVICE_NAME}"
##    HELM_PATH: ./deploy/helm
#  script:
#    - echo ${CI_REGISTRY}
#    - echo ${$CI_REGISTRY_USER}
#    - echo ${$CI_JOB_TOKEN}
#    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_HASH}
#    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:${SERVICE_NAME}-${CI_PIPELINE_ID}
#  only:
#    - 27271-Add-Deploy-Stage-To-Pipeline
