include:
  - project: 'gte-internal/ci-cd/essential'
    ref: "0.1.4"
    file: '/ci-templates/.deployment.yml'
  - project: 'gte-internal/ci-cd/essential'
    ref: "0.1.2"
    file: '/ci-templates/.container.yml'
  - project: 'gte-internal/ci-cd/e2e-testing'
    ref: "0.1"
    file: '/ci-templates/.e2e-tests.yml'
  - project: 'gte-internal/ci-cd/deployment-with-pact'
    ref: "0.1"
    file: '/ci-templates/.deployment-with-pact.yml'


stages:
  - build
#  - container
#  - deploy-to-dev


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  SERVICE_NAME: identity-server-poc
  IMAGE: repository.godeltech.com:18443/python:3.9-slim-buster
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/

build-and-test:
  stage: build
  image: ${IMAGE}
  variables:
    SERVICE: "${SERVICE_NAME}"
    ENV_FOR_DYNACONF: development
  script:
    - apt-get update && pip install poetry
    - printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
    - apt-get install dialog apt-utils -y
    - apt-get install postgresql -y
#    - runuser -l postgres -c "psql -c \"ALTER ROLE postgres WITH PASSWORD 'postgres';\""
#    - runuser -l postgres -c "psql -c \"CREATE DATABASE is_db;\""
    - apt-get install -y build-essential libpq-dev gettext make
    - poetry export -f requirements.txt --output requirements.txt --without-hashes --dev
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --no-cache-dir --upgrade -r requirements.txt
    - make test
  rules:
    - when: always


##################
## CONTAINER
##################

#container:docker-build:
#  extends: .docker-build-artifact
#  only:
#    - Configure-CI-CD-pipeline
#
#
#deploy-to-dev:
#  extends: .deploy-to-dev-ext
#  stage: deploy-to-dev
#  script:
#    - echo ${STAGE_IMAGE_PATH}
#    - echo ${CI_REGISTRY}
#    - echo ${CI_DEPLOY_USER}
#    - echo ${CI_DEPLOY_PASSWORD}
#    - echo ${CI_JOB_TOKEN}
#    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_HASH}
#    - echo ${CI_PIPELINE_ID}
#    - echo ${SERVICE_NAME}
#    - echo ${CI_ENVIRONMENT_NAME}
#    - echo ${CI_PROJECT_PATH}
#    - echo ${CONTAINER_REGISTRY_PROXY}
#    - echo ${CI_PIPELINE_ID}
#    - echo ${SERVICE_NAME}
#    - echo ${CI_COMMIT_HASH}
#  variables:
#    ENV_FOR_DYNACONF: development
#    SERVICE: "${SERVICE_NAME}"
#    HELM_PATH: ./chart
#  only:
#    - Configure-CI-CD-pipeline