exclude: 'migrations|.git'
default_stages: [ commit ]
fail_fast: true


repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^factories/data/|^tests/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
        exclude: ^deploy/|^sample_deploy/
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
        language_version: python3
