exclude: 'migrations|.git'
default_stages: [ commit ]
fail_fast: true


repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^factories/data/|^tests/|^src

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        exclude: ^tests/|src/main


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
        exclude: ^deploy/|^chart/
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
        language_version: python3


  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.11.0
    hooks:
      - id: deptry
        args: [ "--skip-missing" ]
