version: '3'

services:
  postgres:
    container_name: postgres2
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: is_db
    restart: on-failure
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  redis:
    container_name: redis2
    image: redis
    ports:
      - 6379:6379
