apiVersion: v1
kind: Secret
metadata:
  name: isp
  labels:
    app: {{ .Values.application.name  }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
