apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "identity-server-poc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "identity-server-poc.name" . }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: gcp
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "identity-server-poc.chart" . }}
data:
  settings.json: {{ include "identity-server-poc.configData" . | quote }}
