apiVersion: v1
kind: Secret
metadata:
  name: gte-internal-python-identity-server-poc
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "identity-server-poc.imagePullSecret" . }}
