apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: { .Values.application.name }}
  template:
    metadata:
      labels:
        app: { .Values.application.name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.application.image }}
        imagePullPolicy: IfNotPresent
        resources: {{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.application.port }}
