apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName | lower }}-cr
  labels:
    app: {{ .Values.applicationName  }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
