apiVersion: v1
kind: Secret
metadata:
  name: {{ template "identity-server-poc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "identity-server-poc.name" . }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "identity-server-poc.chart" . }}
type: Opaque
data:
  secret.yaml: {{ include "identity-server-poc.secretData" . | b64enc }}
