replicaCount: 1

application:
  name: sample-helm-cicd-demo
  port: 80


imagePullSecret:
  server: gitlab.godeltech.com:4567
  username: xxx
  password: "xxx"
  email: "noreply@godeltech.com"


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
