name: Report a bug
description: Errors and regression reports with complete reproducing test cases.
body:
  - type: markdown
    attributes:
      value: "

**GUIDELINES FOR REPORTING BUGS**

1. a **succinct description of the problem** - typically a line or two at most

2. succinct, dependency-free code which reproduces the problem, otherwise known as an MCVE.

3. complete stack traces for all errors - please avoid screenshots, use formatted text inside issues

4. Other things as applicable.
"
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Assumes cpython unless otherwise stated, e.g. 3.10, 3.11, pypy.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: "
Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example here.
"
      placeholder: "# Insert code here (text area already python formatted)"
      render: python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: "
Provide the complete text of any errors/warnings received **including the complete stack trace, if applicable**.
"
      placeholder: "# Copy the complete stack trace and error message here"
      value: "\
```

# Copy the complete stack trace and error message here.

```
"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Have a nice day!**"