# App
application:
  name: isp
  image: levigoldman/identity
  replicaCount: 1
  port: 8000
  domain: rnd-identityserver-dev.godeltech.com


# Redis
redis:
  image: redis
  replicaCount: 1
  name: redis
  port: 6379


# Parameters for the secret containing ContainerRegistry's credentials
imagePullSecret:
  server: ""
  username: xxx
  password: "xxx"
  email: "noreply@godeltech.com"


# Application Service properties
service:
  port: 8000
  targetPort: 8000
  type: ClusterIP
