init:
  image: "alpine:3.8"
  imagePullPolicy: IfNotPresent


# ------------------------------------------------------------------------------
# Application
# -----------------------------------------------------------------------------
application:
  name: identity-server-poc
  namespace: innovation
  image: gitlab.godeltech.com:4567/gte-internal/python/identity-server-poc:latest
  domain: rnd-identityserver-dev.godeltech.com
  port: 8000


# ------------------------------------------------------------------------------
# Application image version
# -----------------------------------------------------------------------------
imagePullSecret:
  server: gitlab.godeltech.com:4567
  username: xxx
  password: "xxx"


# ------------------------------------------------------------------------------
# Application Service properties
# -----------------------------------------------------------------------------
service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

## How many instances to run
replicaCount: 1


# ------------------------------------------------------------------------------
# Application resources for the deployment
# -----------------------------------------------------------------------------
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"
