[development]
dynaconf_merge = true

[development.db]
echo = true
url = "postgresql+asyncpg://identity-server-dev-user:dsPNWv2mmBhFBdz1XP7N@192.168.80.100:5432/identity-server-dev-db"
max_connection_count = 10
