[development]
dynaconf_merge = true

[development.db]
echo = true
#url = "postgresql+asyncpg://postgres:postgres@localhost:5432/is_db"
url = "postgresql+asyncpg://test:test@172.18.0.1:5463/test"
#url = "postgresql+asyncpg://test:test@localhost:5463/test"
max_connection_count = 10
