[docker]
dynaconf_merge = true


[docker.db]
echo = true
url = "postgresql+asyncpg://postgres:postgres@localhost:5432/is_db"
max_connection_count = 10

[docker.celery]
db_cleaner_crone = '{"minute": "0", "hour": "*" }'