[test]
dynaconf_merge = true


[test.db]
echo = true
url = "postgresql+asyncpg://test:test@localhost:5465/test"
max_connection_count = 10

[test.celery]
db_cleaner_crone = '{"minute": "0", "hour": "2"}'