"""users and resource related migrationn with corrections

Revision ID: 007a74292339
Revises: 1bda0ab9f1fa
Create Date: 2022-12-01 09:04:48.415372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007a74292339'
down_revision = '1bda0ab9f1fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('claim_type', sa.String(), nullable=True),
    sa.Column('claim_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('security_stamp', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_number_confirmed', sa.Boolean(), nullable=True),
    sa.Column('two_factors_enabled', sa.Boolean(), nullable=True),
    sa.Column('lockout_end_date_utc', sa.Date(), nullable=True),
    sa.Column('lockout_enabled', sa.Boolean(), nullable=True),
    sa.Column('access_failed_count', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ApiResource', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ApiResource'], ['api_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ApiResource', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('emphasize', sa.Boolean(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('show_in_discovery_document', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ApiResource'], ['api_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ApiResource', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ApiResource'], ['api_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_team',
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    op.create_table('user_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('User', sa.Integer(), nullable=True),
    sa.Column('login_provider', sa.String(), nullable=False),
    sa.Column('provider_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['User'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'login_provider', 'provider_key'),
    sa.UniqueConstraint('login_provider'),
    sa.UniqueConstraint('provider_key')
    )
    op.create_table('api_scope_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ApiScope', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ApiScope'], ['api_scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['client_id'])
    op.drop_table('api_scope_claims')
    op.drop_table('user_logins')
    op.drop_table('project_team')
    op.drop_table('api_secrets')
    op.drop_table('api_scopes')
    op.drop_table('api_claims')
    op.drop_table('users')
    op.drop_table('user_claims')
    op.drop_table('roles')
    op.drop_table('api_resources')
    # ### end Alembic commands ###
