"""smahit

Revision ID: 00e111b0fb4a
Revises: 03c0bec69e12
Create Date: 2023-02-08 16:32:23.407079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e111b0fb4a'
down_revision = '03c0bec69e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_claims_User_fkey', 'user_claims', type_='foreignkey')
    op.create_foreign_key(None, 'user_claims', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.create_foreign_key('user_claims_User_fkey', 'user_claims', 'users', ['User'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'user_id')
    # ### end Alembic commands ###
