"""userclaim choices

Revision ID: 011951c0d57d
Revises: ceebcca24ed7
Create Date: 2023-02-08 12:33:20.195820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011951c0d57d'
down_revision = 'ceebcca24ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'access_token_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'protocol_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'refresh_token_expiration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'refresh_token_usage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_claims', 'claim_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'claim_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'refresh_token_usage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'refresh_token_expiration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'protocol_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'access_token_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
