"""smahit

Revision ID: 03c0bec69e12
Revises: 9f901a0e330c
Create Date: 2023-02-08 16:29:54.852766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c0bec69e12'
down_revision = '9f901a0e330c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
