"""draft3

Revision ID: 06cdaa004dee
Revises: b9090d63db5b
Create Date: 2023-02-09 16:27:35.913295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cdaa004dee'
down_revision = 'b9090d63db5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persistent_grant_type_id'], ['persistent_grant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persistent_grants')
    # ### end Alembic commands ###
