"""draft

Revision ID: 0a0fd4cf2651
Revises: 9e0ff6ff2721
Create Date: 2023-02-09 14:30:17.326131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0fd4cf2651'
down_revision = '9e0ff6ff2721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('claim_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.drop_column('user_claims', 'claim_type')
    # ### end Alembic commands ###
