"""draft4

Revision ID: 0ababf8a3741
Revises: 40e0efbeeda8
Create Date: 2023-02-10 12:18:13.242082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ababf8a3741'
down_revision = '40e0efbeeda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_grants', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
