"""client choices

Revision ID: 0d9ef6f610e0
Revises: 0b147f170369
Create Date: 2023-02-08 14:28:09.728262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ef6f610e0'
down_revision = '0b147f170369'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
