"""smahit

Revision ID: 0e7b4f3cb750
Revises: 0ee1836133b3
Create Date: 2023-02-08 21:09:06.116583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7b4f3cb750'
down_revision = '0ee1836133b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
