"""smahit

Revision ID: 0ee1836133b3
Revises: a6025e7b173a
Create Date: 2023-02-08 20:59:01.580904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee1836133b3'
down_revision = 'a6025e7b173a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('refresh_token_expiration_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('refresh_token_usage_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.add_column('clients', sa.Column('protocol_type_type', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_type', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'clients', 'refresh_token_usage_types', ['refresh_token_usage_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_expiration_types', ['refresh_token_expiration_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'protocol_types', ['protocol_type_type'], ['type'], ondelete='CASCADE')
    op.drop_column('clients', 'protocol_type')
    op.drop_column('clients', 'refresh_token_usage')
    op.drop_column('clients', 'refresh_token_expiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('refresh_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('protocol_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'refresh_token_usage_type')
    op.drop_column('clients', 'refresh_token_expiration_type')
    op.drop_column('clients', 'protocol_type_type')
    op.drop_table('refresh_token_usage_types')
    op.drop_table('refresh_token_expiration_types')
    op.drop_table('protocol_types')
    # ### end Alembic commands ###
