"""restore columns

Revision ID: 12065ba2f810
Revises: 26a461ea64dc
Create Date: 2023-02-09 13:36:52.620567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12065ba2f810'
down_revision = '26a461ea64dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('type_of_grant', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['type_of_grant'], ['id'], ondelete='CASCADE')
    op.add_column('user_claims', sa.Column('claim_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.drop_column('user_claims', 'claim_type')
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'type_of_grant')
    # ### end Alembic commands ###
