"""draft3

Revision ID: 1276436de755
Revises: ca5d6fa00047
Create Date: 2023-02-09 16:36:10.255559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1276436de755'
down_revision = 'ca5d6fa00047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('access_token_type_type', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_persistent_grant_type_id_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'access_token_types', ['access_token_type_type'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'persistent_grant_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('persistent_grant_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_persistent_grant_type_id_fkey', 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'access_token_type_type')
    # ### end Alembic commands ###
