"""draft4

Revision ID: 179422e294f2
Revises: fab8402269fd
Create Date: 2023-02-10 13:05:22.361247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179422e294f2'
down_revision = 'fab8402269fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('key', sa.String(length=512), nullable=False))
    op.create_unique_constraint(None, 'persistent_grants', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='unique')
    op.drop_column('persistent_grants', 'key')
    # ### end Alembic commands ###
