"""draft4

Revision ID: 19cbaa068b2d
Revises: a107eeaaee3c
Create Date: 2023-02-10 14:46:19.233943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cbaa068b2d'
down_revision = 'a107eeaaee3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
