"""Cascade Delete

Revision ID: 1a9ad0f506df
Revises: d4e782d78fac
Create Date: 2023-01-30 17:56:41.637537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9ad0f506df'
down_revision = 'd4e782d78fac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grants_subject_id_fkey1', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'users', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_logins_User_fkey', 'user_logins', type_='foreignkey')
    op.create_foreign_key(None, 'user_logins', 'users', ['User'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logins', type_='foreignkey')
    op.create_foreign_key('user_logins_User_fkey', 'user_logins', 'users', ['User'], ['id'])
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_subject_id_fkey1', 'persistent_grants', 'users', ['subject_id'], ['id'])
    # ### end Alembic commands ###
