"""add client_id into grant

Revision ID: 1bda0ab9f1fa
Revises: 48e4720ceb05
Create Date: 2022-11-30 11:25:36.574334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bda0ab9f1fa'
down_revision = '48e4720ceb05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'persistent_grants', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###
