"""smahit

Revision ID: 1d650ea96c78
Revises: 4dd2492a3d91
Create Date: 2023-02-08 17:53:43.640282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d650ea96c78'
down_revision = '4dd2492a3d91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('protocol_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('refresh_token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('refresh_token_usage_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('clients', sa.Column('access_token_type_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('protocol_type_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clients', 'refresh_token_usage_types', ['refresh_token_usage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'protocol_types', ['protocol_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_types', ['refresh_token_expiration_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'access_token_types', ['access_token_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'protocol_type')
    op.drop_column('clients', 'refresh_token_expiration')
    op.drop_column('clients', 'access_token_type')
    op.drop_column('clients', 'refresh_token_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('refresh_token_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('access_token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('protocol_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'refresh_token_usage_id')
    op.drop_column('clients', 'refresh_token_expiration_id')
    op.drop_column('clients', 'protocol_type_id')
    op.drop_column('clients', 'access_token_type_id')
    op.drop_table('refresh_token_usage_types')
    op.drop_table('refresh_token_types')
    op.drop_table('protocol_types')
    op.drop_table('access_token_types')
    # ### end Alembic commands ###
