"""smahit

Revision ID: 207968b59e47
Revises: aa442f97c8d1
Create Date: 2023-02-09 12:59:40.554494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207968b59e47'
down_revision = 'aa442f97c8d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'persistent_grant_types', ['type_of_grant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grant_types', type_='unique')
    # ### end Alembic commands ###
