"""client id for grant

Revision ID: 2b4922944b7b
Revises: 007a74292339
Create Date: 2022-12-02 08:57:09.311839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4922944b7b'
down_revision = '86b69cccf027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'persistent_grants', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###
