"""client_scopes_update

Revision ID: 2da57dbf1b95
Revises: 4e5fff99e064
Create Date: 2023-06-12 12:21:16.473567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da57dbf1b95'
down_revision = '4e5fff99e064'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_scopes', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('client_scopes', sa.Column('scope_id', sa.Integer(), nullable=True))
    op.add_column('client_scopes', sa.Column('claim_id', sa.Integer(), nullable=False))
    op.drop_constraint('client_scopes_client_id_key', 'client_scopes', type_='unique')
    op.create_foreign_key(None, 'client_scopes', 'api_scope_claim_types', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_scopes', 'api_resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_scopes', 'api_scopes', ['scope_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_scopes', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_scopes', sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.create_unique_constraint('client_scopes_client_id_key', 'client_scopes', ['client_id'])
    op.drop_column('client_scopes', 'claim_id')
    op.drop_column('client_scopes', 'scope_id')
    op.drop_column('client_scopes', 'resource_id')
    # ### end Alembic commands ###
