"""empty message

Revision ID: 2efbc00f79d7
Revises: 5c5968696703
Create Date: 2023-02-14 10:28:43.803822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efbc00f79d7'
down_revision = '5c5968696703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
