"""smahit

Revision ID: 34b0c74cc816
Revises: a9a2bc090ece
Create Date: 2023-02-09 12:42:00.584634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b0c74cc816'
down_revision = 'a9a2bc090ece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('type_of_grant', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_type_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['type_of_grant'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_type_fkey', 'persistent_grants', 'persistent_grant_types', ['type'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'type_of_grant')
    # ### end Alembic commands ###
