"""draft4

Revision ID: 358b2637ef85
Revises: 3d0c7ddbbc78
Create Date: 2023-02-10 12:14:07.464878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358b2637ef85'
down_revision = '3d0c7ddbbc78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grants_persistent_grant_type_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'persistent_grant_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('persistent_grant_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('persistent_grants_persistent_grant_type_id_fkey', 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
