"""draft4

Revision ID: 37702cbec292
Revises: bd96101b624c
Create Date: 2023-02-10 12:48:18.598082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37702cbec292'
down_revision = 'bd96101b624c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
