"""smahit

Revision ID: 3936b3a6f6a2
Revises: 647fcfc22572
Create Date: 2023-02-09 12:39:13.456905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3936b3a6f6a2'
down_revision = '647fcfc22572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grant_types_type_fkey', 'persistent_grant_types', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('persistent_grant_types_type_fkey', 'persistent_grant_types', 'user_claim_types', ['type'], ['type'], ondelete='CASCADE')
    # ### end Alembic commands ###
