"""draft4

Revision ID: 3b375964ae7a
Revises: 19cbaa068b2d
Create Date: 2023-02-10 14:53:08.599947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b375964ae7a'
down_revision = '19cbaa068b2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
