"""id_came_back

Revision ID: 3d01c5994bd7
Revises: 6a65a2974456
Create Date: 2023-02-10 16:49:07.180379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d01c5994bd7'
down_revision = '6a65a2974456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_claims', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_claims', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_cors_origins', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_cors_origins', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_grant_types', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_grant_types', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_id_restrictions', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_id_restrictions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_post_logout_redirect_uris', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_post_logout_redirect_uris', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_redirect_uris', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_redirect_uris', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_scopes', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_scopes', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('client_secrets', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_secrets', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_secrets', type_='foreignkey')
    op.drop_column('client_secrets', 'client_id')
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.drop_column('client_scopes', 'client_id')
    op.drop_constraint(None, 'client_redirect_uris', type_='foreignkey')
    op.drop_column('client_redirect_uris', 'client_id')
    op.drop_constraint(None, 'client_post_logout_redirect_uris', type_='foreignkey')
    op.drop_column('client_post_logout_redirect_uris', 'client_id')
    op.drop_constraint(None, 'client_id_restrictions', type_='foreignkey')
    op.drop_column('client_id_restrictions', 'client_id')
    op.drop_constraint(None, 'client_grant_types', type_='foreignkey')
    op.drop_column('client_grant_types', 'client_id')
    op.drop_constraint(None, 'client_cors_origins', type_='foreignkey')
    op.drop_column('client_cors_origins', 'client_id')
    op.drop_constraint(None, 'client_claims', type_='foreignkey')
    op.drop_column('client_claims', 'client_id')
    # ### end Alembic commands ###
