"""draft4

Revision ID: 3d0c7ddbbc78
Revises: e28eeb6a87b1
Create Date: 2023-02-10 09:27:48.636045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d0c7ddbbc78'
down_revision = 'e28eeb6a87b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('access_token_type_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('protocol_type_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_type_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('clients_protocol_type_type_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('clients_access_token_type_type_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('clients_refresh_token_usage_type_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('clients_refresh_token_expiration_type_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'protocol_types', ['protocol_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_usage_types', ['refresh_token_usage_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_expiration_types', ['refresh_token_expiration_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'access_token_types', ['access_token_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'access_token_type_type')
    op.drop_column('clients', 'refresh_token_expiration_type')
    op.drop_column('clients', 'refresh_token_usage_type')
    op.drop_column('clients', 'protocol_type_type')
    op.drop_column('refresh_token_usage_types', 'created_at')
    op.drop_column('refresh_token_usage_types', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token_usage_types', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('refresh_token_usage_types', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('protocol_type_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('access_token_type_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_refresh_token_expiration_type_fkey', 'clients', 'refresh_token_expiration_types', ['refresh_token_expiration_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('clients_refresh_token_usage_type_fkey', 'clients', 'refresh_token_usage_types', ['refresh_token_usage_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('clients_access_token_type_type_fkey', 'clients', 'access_token_types', ['access_token_type_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('clients_protocol_type_type_fkey', 'clients', 'protocol_types', ['protocol_type_type'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'refresh_token_usage_type_id')
    op.drop_column('clients', 'refresh_token_expiration_type_id')
    op.drop_column('clients', 'protocol_type_id')
    op.drop_column('clients', 'access_token_type_id')
    # ### end Alembic commands ###
