"""draft4

Revision ID: 40e0efbeeda8
Revises: 358b2637ef85
Create Date: 2023-02-10 12:14:40.089604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e0efbeeda8'
down_revision = '358b2637ef85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persistent_grant_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_grant_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_of_grant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persistent_grant_types_pkey')
    )
    # ### end Alembic commands ###
