"""Added code challenge tables

Revision ID: 432f08914e0c
Revises: f217db047f72
Create Date: 2023-05-31 14:10:20.545247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432f08914e0c'
down_revision = 'f217db047f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_challenge_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('code_challenge', sa.String(), nullable=False),
    sa.Column('code_challenge_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_challenge_method_id'], ['code_challenge_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_challenges')
    op.drop_table('code_challenge_methods')
    # ### end Alembic commands ###
