"""check

Revision ID: 4d7feb566ec6
Revises: dd595b33f54e
Create Date: 2022-12-23 12:03:23.328498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d7feb566ec6'
down_revision = 'dd595b33f54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persistent_grants', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persistent_grants', 'data',
               existing_type=sa.String(length=2048),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
