"""smahit

Revision ID: 4dd2492a3d91
Revises: 00e111b0fb4a
Create Date: 2023-02-08 17:34:32.276503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd2492a3d91'
down_revision = '00e111b0fb4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('user_claims', sa.Column('claim_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'claim_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('claim_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.drop_column('user_claims', 'claim_type_id')
    op.drop_table('user_claim_types')
    # ### end Alembic commands ###
