"""scope_for_persistant_grant

Revision ID: 4e5fff99e064
Revises: f217db047f72
Create Date: 2023-06-05 10:29:23.735336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5fff99e064'
down_revision = 'f217db047f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('scope', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_grants', 'scope')
    # ### end Alembic commands ###
