"""draft4

Revision ID: 509eb2c07da4
Revises: 5bf299aed4ae
Create Date: 2023-02-10 12:58:15.672902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509eb2c07da4'
down_revision = '5bf299aed4ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persistent_grants', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###
