"""smahit

Revision ID: 5193f3877565
Revises: ca5484af536a
Create Date: 2023-02-09 12:16:40.062228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5193f3877565'
down_revision = 'ca5484af536a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('claim_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_claims', 'claim_type')
    # ### end Alembic commands ###
