"""smahit

Revision ID: 52d6bc49c778
Revises: d17157d6167d
Create Date: 2023-02-09 12:14:23.858882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d6bc49c778'
down_revision = 'd17157d6167d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('protocol_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('refresh_token_expiration_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('refresh_token_usage_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('user_claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('clients', sa.Column('access_token_type_type', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('protocol_type_type', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_type', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'clients', 'refresh_token_expiration_types', ['refresh_token_expiration_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'access_token_types', ['access_token_type_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_usage_types', ['refresh_token_usage_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'protocol_types', ['protocol_type_type'], ['type'], ondelete='CASCADE')
    op.drop_column('clients', 'access_token_type')
    op.drop_column('clients', 'protocol_type')
    op.drop_column('clients', 'refresh_token_usage')
    op.drop_column('clients', 'refresh_token_expiration')
    op.add_column('user_claims', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_claims_User_fkey', 'user_claims', type_='foreignkey')
    op.create_foreign_key(None, 'user_claims', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.create_foreign_key('user_claims_User_fkey', 'user_claims', 'users', ['User'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'user_id')
    op.add_column('clients', sa.Column('refresh_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('protocol_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('access_token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'refresh_token_usage_type')
    op.drop_column('clients', 'refresh_token_expiration_type')
    op.drop_column('clients', 'protocol_type_type')
    op.drop_column('clients', 'access_token_type_type')
    op.drop_table('user_claim_types')
    op.drop_table('refresh_token_usage_types')
    op.drop_table('refresh_token_expiration_types')
    op.drop_table('protocol_types')
    op.drop_table('access_token_types')
    # ### end Alembic commands ###
