"""chane field name in resource related

Revision ID: 5785b657a0ec
Revises: 7ac0d7f7a6af
Create Date: 2022-12-20 10:49:38.555270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5785b657a0ec'
down_revision = '7ac0d7f7a6af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_claims', sa.Column('api_resources_id', sa.Integer(), nullable=True))
    op.drop_constraint('api_claims_ApiResource_fkey', 'api_claims', type_='foreignkey')
    op.create_foreign_key(None, 'api_claims', 'api_resources', ['api_resources_id'], ['id'])
    op.drop_column('api_claims', 'ApiResource')
    op.add_column('api_scope_claims', sa.Column('api_scopes_id', sa.Integer(), nullable=True))
    op.drop_constraint('api_scope_claims_ApiScope_fkey', 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key(None, 'api_scope_claims', 'api_scopes', ['api_scopes_id'], ['id'])
    op.drop_column('api_scope_claims', 'ApiScope')
    op.add_column('api_scopes', sa.Column('api_resources_id', sa.Integer(), nullable=True))
    op.drop_constraint('api_scopes_ApiResource_fkey', 'api_scopes', type_='foreignkey')
    op.create_foreign_key(None, 'api_scopes', 'api_resources', ['api_resources_id'], ['id'])
    op.drop_column('api_scopes', 'ApiResource')
    op.add_column('api_secrets', sa.Column('api_resources_id', sa.Integer(), nullable=True))
    op.drop_constraint('api_secrets_ApiResource_fkey', 'api_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'api_secrets', 'api_resources', ['api_resources_id'], ['id'])
    op.drop_column('api_secrets', 'ApiResource')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_secrets', sa.Column('ApiResource', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_secrets', type_='foreignkey')
    op.create_foreign_key('api_secrets_ApiResource_fkey', 'api_secrets', 'api_resources', ['ApiResource'], ['id'])
    op.drop_column('api_secrets', 'api_resources_id')
    op.add_column('api_scopes', sa.Column('ApiResource', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_scopes', type_='foreignkey')
    op.create_foreign_key('api_scopes_ApiResource_fkey', 'api_scopes', 'api_resources', ['ApiResource'], ['id'])
    op.drop_column('api_scopes', 'api_resources_id')
    op.add_column('api_scope_claims', sa.Column('ApiScope', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key('api_scope_claims_ApiScope_fkey', 'api_scope_claims', 'api_scopes', ['ApiScope'], ['id'])
    op.drop_column('api_scope_claims', 'api_scopes_id')
    op.add_column('api_claims', sa.Column('ApiResource', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_claims', type_='foreignkey')
    op.create_foreign_key('api_claims_ApiResource_fkey', 'api_claims', 'api_resources', ['ApiResource'], ['id'])
    op.drop_column('api_claims', 'api_resources_id')
    # ### end Alembic commands ###
