"""proper_relations

Revision ID: 5c5968696703
Revises: 3d01c5994bd7
Create Date: 2023-02-10 19:25:23.247418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5968696703'
down_revision = '3d01c5994bd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
