"""draft3

Revision ID: 5db1cd16fa72
Revises: b649b2e6ffb2
Create Date: 2023-02-09 16:17:41.830213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db1cd16fa72'
down_revision = 'b649b2e6ffb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_persistent_grant_type_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'persistent_grant_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('persistent_grant_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_persistent_grant_type_fkey', 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'persistent_grant_type_id')
    # ### end Alembic commands ###
