"""smahit

Revision ID: 5e08c4ad8654
Revises: 34b0c74cc816
Create Date: 2023-02-09 12:42:46.632139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e08c4ad8654'
down_revision = '34b0c74cc816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claim_types', sa.Column('type_of_claim', sa.String(), nullable=True))
    op.drop_constraint('user_claim_types_type_key', 'user_claim_types', type_='unique')
    op.create_unique_constraint(None, 'user_claim_types', ['type_of_claim'])
    op.drop_column('user_claim_types', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claim_types', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claim_types', type_='unique')
    op.create_unique_constraint('user_claim_types_type_key', 'user_claim_types', ['type'])
    op.drop_column('user_claim_types', 'type_of_claim')
    # ### end Alembic commands ###
