"""userclaims-deleted-*string*-row

Revision ID: 64452d4bc925
Revises: 05813da276cf
Create Date: 2022-12-09 11:51:37.342825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64452d4bc925'
down_revision = '05813da276cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
