"""smahit

Revision ID: 647fcfc22572
Revises: bf057577591f
Create Date: 2023-02-09 12:34:01.028977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647fcfc22572'
down_revision = 'bf057577591f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grant_types', sa.Column('type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'persistent_grant_types', 'user_claim_types', ['type'], ['type'], ondelete='CASCADE')
    op.add_column('persistent_grants', sa.Column('type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'type')
    op.drop_constraint(None, 'persistent_grant_types', type_='foreignkey')
    op.drop_column('persistent_grant_types', 'type')
    # ### end Alembic commands ###
