"""draft4

Revision ID: 658b9fee922c
Revises: a4e2ba85cd92
Create Date: 2023-02-10 12:24:13.526623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658b9fee922c'
down_revision = 'a4e2ba85cd92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'persistent_grants', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###
