"""Expiration changed from datetime to int

Revision ID: 6a0d2334ec18
Revises: 873a06aea5d8
Create Date: 2022-12-18 05:09:53.137080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a0d2334ec18'
down_revision = '873a06aea5d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
