"""Client related models with wright type

Revision ID: 6a39c6b2d14b
Revises: 
Create Date: 2022-11-23 10:49:51.432482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a39c6b2d14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('absolute_refresh_token_lifetime', sa.Integer(), nullable=False),
    sa.Column('access_token_lifetime', sa.Integer(), nullable=False),
    sa.Column('access_token_type', sa.String(), nullable=False),
    sa.Column('allow_access_token_via_browser', sa.Boolean(), nullable=False),
    sa.Column('allow_offline_access', sa.Boolean(), nullable=False),
    sa.Column('allow_plain_text_pkce', sa.Boolean(), nullable=False),
    sa.Column('allow_remember_consent', sa.Boolean(), nullable=False),
    sa.Column('always_include_user_claims_id_token', sa.Boolean(), nullable=False),
    sa.Column('always_send_client_claims', sa.Boolean(), nullable=False),
    sa.Column('authorisation_code_lifetime', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_uri', sa.String(), nullable=False),
    sa.Column('enable_local_login', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('identity_token_lifetime', sa.Integer(), nullable=False),
    sa.Column('include_jwt_id', sa.Boolean(), nullable=False),
    sa.Column('logo_uri', sa.String(), nullable=False),
    sa.Column('logout_session_required', sa.Boolean(), nullable=False),
    sa.Column('logout_uri', sa.String(), nullable=False),
    sa.Column('prefix_client_claims', sa.String(), nullable=True),
    sa.Column('protocol_type', sa.String(), nullable=False),
    sa.Column('refresh_token_expiration', sa.String(), nullable=False),
    sa.Column('refresh_token_usage', sa.String(), nullable=False),
    sa.Column('require_client_secret', sa.Boolean(), nullable=False),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.Column('require_pkce', sa.Boolean(), nullable=False),
    sa.Column('sliding_refresh_token_lifetime', sa.Integer(), nullable=False),
    sa.Column('update_access_token_claims_on_refresh', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('client_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_cors_origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_grant_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('client_id_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_post_logout_redirect_uris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_logout_redirect_uri', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_redirect_uris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('client_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_secrets')
    op.drop_table('client_scopes')
    op.drop_table('client_redirect_uris')
    op.drop_table('client_post_logout_redirect_uris')
    op.drop_table('client_id_restrictions')
    op.drop_table('client_grant_types')
    op.drop_table('client_cors_origins')
    op.drop_table('client_claims')
    op.drop_table('clients')
    # ### end Alembic commands ###
