"""draft4

Revision ID: 6ab86a22919b
Revises: 658b9fee922c
Create Date: 2023-02-10 12:30:25.108716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab86a22919b'
down_revision = '658b9fee922c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('client_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
