"""draft3

Revision ID: 70912eb7c26f
Revises: 1276436de755
Create Date: 2023-02-09 16:38:08.029339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70912eb7c26f'
down_revision = '1276436de755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
