"""client choices

Revision ID: 7130fa0db93f
Revises: 011951c0d57d
Create Date: 2023-02-08 12:44:46.615014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7130fa0db93f'
down_revision = '011951c0d57d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'User',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'User',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
