"""smahit

Revision ID: 72fee44410a4
Revises: 5193f3877565
Create Date: 2023-02-09 12:19:48.816157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fee44410a4'
down_revision = '5193f3877565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
