"""draft4

Revision ID: 7541582ff098
Revises: 70912eb7c26f
Create Date: 2023-02-10 09:03:57.124193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7541582ff098'
down_revision = '70912eb7c26f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_type')
    )
    op.create_table('api_scope_claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scope_claim_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_claim_type')
    )
    op.create_table('api_secrets_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('secret_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_type')
    )
    op.add_column('api_claims', sa.Column('claim_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'api_claims', 'api_claim_types', ['claim_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_claims', 'type')
    op.add_column('api_scope_claims', sa.Column('scope_claim_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'api_scope_claims', 'api_claim_types', ['scope_claim_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_scope_claims', 'type')
    op.alter_column('api_scopes', 'api_resources_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('api_secrets', sa.Column('secret_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'api_secrets', 'api_secrets_types', ['secret_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_secrets', 'type')
    op.add_column('persistent_grants', sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_access_token_type_type_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'access_token_type_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('access_token_type_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_access_token_type_type_fkey', 'persistent_grants', 'access_token_types', ['access_token_type_type'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'persistent_grant_type_id')
    op.add_column('api_secrets', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_secrets', type_='foreignkey')
    op.drop_column('api_secrets', 'secret_type_id')
    op.alter_column('api_scopes', 'api_resources_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('api_scope_claims', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_scope_claims', type_='foreignkey')
    op.drop_column('api_scope_claims', 'scope_claim_type_id')
    op.add_column('api_claims', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_claims', type_='foreignkey')
    op.drop_column('api_claims', 'claim_type_id')
    op.drop_table('api_secrets_types')
    op.drop_table('api_scope_claim_types')
    op.drop_table('api_claim_types')
    # ### end Alembic commands ###
