"""draft4

Revision ID: 76b5e5b4caff
Revises: 3b375964ae7a
Create Date: 2023-02-10 14:56:11.693143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b5e5b4caff'
down_revision = '3b375964ae7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_logins_login_provider_key', 'user_logins', type_='unique')
    op.drop_constraint('user_logins_provider_key_key', 'user_logins', type_='unique')
    op.drop_column('user_logins', 'login_provider')
    op.drop_column('user_logins', 'provider_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('provider_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_logins', sa.Column('login_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_logins_provider_key_key', 'user_logins', ['provider_key'])
    op.create_unique_constraint('user_logins_login_provider_key', 'user_logins', ['login_provider'])
    # ### end Alembic commands ###
