"""Cascade Delete

Revision ID: 7723d1e46f7b
Revises: 1a9ad0f506df
Create Date: 2023-01-30 18:00:50.521768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7723d1e46f7b'
down_revision = '1a9ad0f506df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_claims_api_resources_id_fkey', 'api_claims', type_='foreignkey')
    op.create_foreign_key(None, 'api_claims', 'api_resources', ['api_resources_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('api_scope_claims_api_scopes_id_fkey', 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key(None, 'api_scope_claims', 'api_scopes', ['api_scopes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('api_scopes_api_resources_id_fkey', 'api_scopes', type_='foreignkey')
    op.create_foreign_key(None, 'api_scopes', 'api_resources', ['api_resources_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('api_secrets_api_resources_id_fkey', 'api_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'api_secrets', 'api_resources', ['api_resources_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('client_claims_client_id_fkey', 'client_claims', type_='foreignkey')
    op.create_foreign_key(None, 'client_claims', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_cors_origins_client_id_fkey', 'client_cors_origins', type_='foreignkey')
    op.create_foreign_key(None, 'client_cors_origins', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_grant_types_client_id_fkey', 'client_grant_types', type_='foreignkey')
    op.create_foreign_key(None, 'client_grant_types', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_id_restrictions_client_id_fkey', 'client_id_restrictions', type_='foreignkey')
    op.create_foreign_key(None, 'client_id_restrictions', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_post_logout_redirect_uris_client_id_fkey', 'client_post_logout_redirect_uris', type_='foreignkey')
    op.create_foreign_key(None, 'client_post_logout_redirect_uris', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_redirect_uris_client_id_fkey', 'client_redirect_uris', type_='foreignkey')
    op.create_foreign_key(None, 'client_redirect_uris', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_scopes_client_id_fkey', 'client_scopes', type_='foreignkey')
    op.create_foreign_key(None, 'client_scopes', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('client_secrets_client_id_fkey', 'client_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'client_secrets', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('identity_claims_identity_resource_id_fkey', 'identity_claims', type_='foreignkey')
    op.create_foreign_key(None, 'identity_claims', 'identity_resources', ['identity_resource_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('persistent_grants_subject_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key('persistent_grants_subject_id_fkey', 'persistent_grants', 'users', ['subject_id'], ['id'])
    op.drop_constraint(None, 'identity_claims', type_='foreignkey')
    op.create_foreign_key('identity_claims_identity_resource_id_fkey', 'identity_claims', 'identity_resources', ['identity_resource_id'], ['id'])
    op.drop_constraint(None, 'client_secrets', type_='foreignkey')
    op.create_foreign_key('client_secrets_client_id_fkey', 'client_secrets', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.create_foreign_key('client_scopes_client_id_fkey', 'client_scopes', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_redirect_uris', type_='foreignkey')
    op.create_foreign_key('client_redirect_uris_client_id_fkey', 'client_redirect_uris', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_post_logout_redirect_uris', type_='foreignkey')
    op.create_foreign_key('client_post_logout_redirect_uris_client_id_fkey', 'client_post_logout_redirect_uris', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_id_restrictions', type_='foreignkey')
    op.create_foreign_key('client_id_restrictions_client_id_fkey', 'client_id_restrictions', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_grant_types', type_='foreignkey')
    op.create_foreign_key('client_grant_types_client_id_fkey', 'client_grant_types', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_cors_origins', type_='foreignkey')
    op.create_foreign_key('client_cors_origins_client_id_fkey', 'client_cors_origins', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'client_claims', type_='foreignkey')
    op.create_foreign_key('client_claims_client_id_fkey', 'client_claims', 'clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 'api_secrets', type_='foreignkey')
    op.create_foreign_key('api_secrets_api_resources_id_fkey', 'api_secrets', 'api_resources', ['api_resources_id'], ['id'])
    op.drop_constraint(None, 'api_scopes', type_='foreignkey')
    op.create_foreign_key('api_scopes_api_resources_id_fkey', 'api_scopes', 'api_resources', ['api_resources_id'], ['id'])
    op.drop_constraint(None, 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key('api_scope_claims_api_scopes_id_fkey', 'api_scope_claims', 'api_scopes', ['api_scopes_id'], ['id'])
    op.drop_constraint(None, 'api_claims', type_='foreignkey')
    op.create_foreign_key('api_claims_api_resources_id_fkey', 'api_claims', 'api_resources', ['api_resources_id'], ['id'])
    # ### end Alembic commands ###
