"""Add device_code_lifetime column to client table

Revision ID: 7a5ee88941c1
Revises: a748c875b0dd
Create Date: 2023-04-20 11:31:22.795925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a5ee88941c1"
down_revision = "a748c875b0dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "device_code_lifetime",
            sa.Integer(),
            nullable=False,
            server_default="600",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "device_code_lifetime")
    # ### end Alembic commands ###
