"""userclaims-deleted-*string*-row

Revision ID: 7ac0d7f7a6af
Revises: 64452d4bc925
Create Date: 2022-12-09 11:55:42.549045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac0d7f7a6af'
down_revision = '64452d4bc925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
