"""draft4

Revision ID: 7b75b4b943a4
Revises: 76b5e5b4caff
Create Date: 2023-02-10 14:58:37.440585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b75b4b943a4'
down_revision = '76b5e5b4caff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('login_provider', sa.String(), nullable=False))
    op.add_column('user_logins', sa.Column('provider_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_logins', ['login_provider'])
    op.create_unique_constraint(None, 'user_logins', ['provider_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logins', type_='unique')
    op.drop_constraint(None, 'user_logins', type_='unique')
    op.drop_column('user_logins', 'provider_key')
    op.drop_column('user_logins', 'login_provider')
    # ### end Alembic commands ###
