"""Updated Persisted Grants

Revision ID: 86b69cccf027
Revises: 6a0d2334ec18
Create Date: 2022-12-18 18:05:01.503725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b69cccf027'
down_revision = '6a0d2334ec18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persistent_grants', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'persistent_grants', ['key'])
    op.create_foreign_key(None, 'persistent_grants', 'users', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_constraint(None, 'persistent_grants', type_='unique')
    op.alter_column('persistent_grants', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('persistent_grants', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('persistent_grants', 'updated_at')
    op.drop_column('persistent_grants', 'created_at')
    # ### end Alembic commands ###
