"""blacklist_update

Revision ID: 885a98137552
Revises: e0e2a2ca00a8
Create Date: 2023-03-06 18:55:14.473267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885a98137552'
down_revision = 'e0e2a2ca00a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('blacklisted_tokens', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('blacklisted_tokens_token_key', 'blacklisted_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('blacklisted_tokens_token_key', 'blacklisted_tokens', ['token'])
    op.drop_column('blacklisted_tokens', 'updated_at')
    op.drop_column('blacklisted_tokens', 'created_at')
    # ### end Alembic commands ###
