"""checkconstraint checkconstraint pers grants

Revision ID: 8926453f268f
Revises: a0d718056971
Create Date: 2023-02-07 17:41:39.067782

"""
from alembic import op
import sqlalchemy as sa
from src.data_access.postgresql.tables.persistent_grant import TYPES_OF_GRANTS

def from_list_of_str_to_str(values):
    result = ""
    for value in values:
        result += "\'"+value+"\', "
    return result[:-2]

# revision identifiers, used by Alembic.
revision = '8926453f268f'
down_revision = 'a0d718056971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "type_in_list",
        "persistent_grants",
        f'"type" IN ({from_list_of_str_to_str(TYPES_OF_GRANTS)})'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
