"""draft4

Revision ID: 90a127114489
Revises: a18b0616f76a
Create Date: 2023-02-10 09:12:12.595887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a127114489'
down_revision = 'a18b0616f76a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_scope_claims_scope_claim_type_id_fkey', 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key(None, 'api_scope_claims', 'api_scope_claim_types', ['scope_claim_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_scope_claims', type_='foreignkey')
    op.create_foreign_key('api_scope_claims_scope_claim_type_id_fkey', 'api_scope_claims', 'api_claim_types', ['scope_claim_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
