"""draft4

Revision ID: 9c2c29b3a199
Revises: 0ababf8a3741
Create Date: 2023-02-10 12:19:49.705069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2c29b3a199'
down_revision = '0ababf8a3741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_grant_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_grant', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('persistent_grants', sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'persistent_grant_type_id')
    op.drop_table('persistent_grant_types')
    # ### end Alembic commands ###
