"""draft2

Revision ID: 9d5f0916522f
Revises: 0a0fd4cf2651
Create Date: 2023-02-09 15:37:25.275634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5f0916522f'
down_revision = '0a0fd4cf2651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('protocol_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('refresh_token_expiration_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('refresh_token_usage_types',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('clients', sa.Column('access_token_type_type', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('protocol_type_type', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_expiration_type', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('refresh_token_usage_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clients', 'refresh_token_usage_types', ['refresh_token_usage_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'protocol_types', ['protocol_type_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'access_token_types', ['access_token_type_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'refresh_token_expiration_types', ['refresh_token_expiration_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'refresh_token_usage_type')
    op.drop_column('clients', 'refresh_token_expiration_type')
    op.drop_column('clients', 'protocol_type_type')
    op.drop_column('clients', 'access_token_type_type')
    op.drop_table('refresh_token_usage_types')
    op.drop_table('refresh_token_expiration_types')
    op.drop_table('protocol_types')
    op.drop_table('access_token_types')
    # ### end Alembic commands ###
