"""draft

Revision ID: 9e0ff6ff2721
Revises: d17157d6167d
Create Date: 2023-02-09 14:29:54.812131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0ff6ff2721'
down_revision = 'd17157d6167d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_grant_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_grant', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_of_grant')
    )
    op.create_table('user_claim_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_claim', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_of_claim')
    )
    op.drop_column('clients', 'refresh_token_expiration')
    op.drop_column('clients', 'refresh_token_usage')
    op.drop_column('clients', 'access_token_type')
    op.drop_column('clients', 'protocol_type')
    op.add_column('persistent_grants', sa.Column('type_of_grant', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_client_id_fkey', 'persistent_grants', type_='foreignkey')
    op.drop_constraint('persistent_grants_subject_id_fkey1', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['type_of_grant'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'subject_id')
    op.drop_column('persistent_grants', 'type')
    op.drop_column('persistent_grants', 'client_id')
    op.add_column('user_claims', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_claims_User_fkey', 'user_claims', type_='foreignkey')
    op.create_foreign_key(None, 'user_claims', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'claim_type')
    op.drop_column('user_claims', 'User')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_claims', sa.Column('claim_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.create_foreign_key('user_claims_User_fkey', 'user_claims', 'users', ['User'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'user_id')
    op.add_column('persistent_grants', sa.Column('client_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('persistent_grants', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('persistent_grants', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_subject_id_fkey1', 'persistent_grants', 'users', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('persistent_grants_client_id_fkey', 'persistent_grants', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'type_of_grant')
    op.add_column('clients', sa.Column('protocol_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('access_token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('user_claim_types')
    op.drop_table('persistent_grant_types')
    # ### end Alembic commands ###
