"""smahit

Revision ID: 9f901a0e330c
Revises: 81ab6eaac3fa
Create Date: 2023-02-08 16:18:34.981117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f901a0e330c'
down_revision = '81ab6eaac3fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'User',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_claims', 'User',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
