"""draft4

Revision ID: a107eeaaee3c
Revises: a83dfe3e3a85
Create Date: 2023-02-10 14:45:21.870130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a107eeaaee3c'
down_revision = 'a83dfe3e3a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_logins_User_fkey', 'user_logins', type_='foreignkey')
    op.create_foreign_key(None, 'user_logins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_logins', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_logins', type_='foreignkey')
    op.create_foreign_key('user_logins_User_fkey', 'user_logins', 'users', ['User'], ['id'], ondelete='CASCADE')
    op.drop_column('user_logins', 'user_id')
    # ### end Alembic commands ###
