"""draft4

Revision ID: a18b0616f76a
Revises: e649137e9e05
Create Date: 2023-02-10 09:07:55.501779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18b0616f76a'
down_revision = 'e649137e9e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
