"""draft4

Revision ID: a4e2ba85cd92
Revises: 9c2c29b3a199
Create Date: 2023-02-10 12:22:47.009629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e2ba85cd92'
down_revision = '9c2c29b3a199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persistent_grants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.drop_column('persistent_grants', 'user_id')
    # ### end Alembic commands ###
