"""smahit

Revision ID: a6025e7b173a
Revises: d17157d6167d
Create Date: 2023-02-08 20:47:02.269219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6025e7b173a'
down_revision = 'd17157d6167d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('user_claim_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.add_column('clients', sa.Column('access_token_type_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'clients', 'access_token_types', ['access_token_type_type'], ['type'], ondelete='CASCADE')
    op.drop_column('clients', 'access_token_type')
    op.add_column('user_claims', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('user_claims_User_fkey', 'user_claims', type_='foreignkey')
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type'], ['type'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_claims', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.create_foreign_key('user_claims_User_fkey', 'user_claims', 'users', ['User'], ['id'], ondelete='CASCADE')
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_claims', 'user_id')
    op.add_column('clients', sa.Column('access_token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'access_token_type_type')
    op.drop_table('user_claim_types')
    op.drop_table('access_token_types')
    # ### end Alembic commands ###
