"""change_authorisation_to_authorization

Revision ID: a748c875b0dd
Revises: 885a98137552
Create Date: 2023-04-19 14:52:49.733489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a748c875b0dd'
down_revision = '885a98137552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('authorization_code_lifetime', sa.Integer(), nullable=False))
    op.drop_column('clients', 'authorisation_code_lifetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('authorisation_code_lifetime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'authorization_code_lifetime')
    # ### end Alembic commands ###
