"""change_authorisation_to_authorization

Revision ID: a748c875b0dd
Revises: 885a98137552
Create Date: 2023-04-19 14:52:49.733489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a748c875b0dd"
down_revision = "885a98137552"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "authorisation_code_lifetime",
        existing_type=sa.INTEGER(),
        nullable=False,
        new_column_name="authorization_code_lifetime",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "authorization_code_lifetime",
        existing_type=sa.INTEGER(),
        nullable=False,
        new_column_name="authorization_code_lifetime",
    )
    # ### end Alembic commands ####
