"""draft4

Revision ID: a83dfe3e3a85
Revises: b5a13fed0b3a
Create Date: 2023-02-10 13:12:25.790207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83dfe3e3a85'
down_revision = 'b5a13fed0b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('grant_data', sa.String(), nullable=False))
    op.drop_column('persistent_grants', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('persistent_grants', 'grant_data')
    # ### end Alembic commands ###
