"""smahit

Revision ID: a9a2bc090ece
Revises: 3936b3a6f6a2
Create Date: 2023-02-09 12:41:08.138246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a2bc090ece'
down_revision = '3936b3a6f6a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grant_types', sa.Column('type_of_grant', sa.String(), nullable=False))
    op.drop_column('persistent_grant_types', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grant_types', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('persistent_grant_types', 'type_of_grant')
    # ### end Alembic commands ###
