"""client_scope_update

Revision ID: a9b3da91b421
Revises: 4e5fff99e064
Create Date: 2023-06-19 08:52:44.920326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b3da91b421'
down_revision = '4e5fff99e064'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_scopes',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['client_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'scope_id')
    )
    op.add_column('client_scopes', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('client_scopes', sa.Column('scope_id', sa.Integer(), nullable=True))
    op.add_column('client_scopes', sa.Column('claim_id', sa.Integer(), nullable=False))
    op.drop_constraint('client_scopes_client_id_key', 'client_scopes', type_='unique')
    op.drop_constraint('client_scopes_client_id_fkey', 'client_scopes', type_='foreignkey')
    op.create_foreign_key(None, 'client_scopes', 'api_scopes', ['scope_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_scopes', 'api_resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_scopes', 'api_scope_claim_types', ['claim_id'], ['id'], ondelete='CASCADE')
    op.drop_column('client_scopes', 'scope')
    op.drop_column('client_scopes', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_scopes', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_scopes', sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.drop_constraint(None, 'client_scopes', type_='foreignkey')
    op.create_foreign_key('client_scopes_client_id_fkey', 'client_scopes', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('client_scopes_client_id_key', 'client_scopes', ['client_id'])
    op.drop_column('client_scopes', 'claim_id')
    op.drop_column('client_scopes', 'scope_id')
    op.drop_column('client_scopes', 'resource_id')
    op.drop_table('clients_scopes')
    # ### end Alembic commands ###
