"""smahit

Revision ID: aa442f97c8d1
Revises: 98b6cf9fbdbd
Create Date: 2023-02-09 12:49:49.088897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa442f97c8d1'
down_revision = '98b6cf9fbdbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
