"""clients_grant_types_many_to_many

Revision ID: ad7385ff7f96
Revises: 9753a31c8deb
Create Date: 2023-03-23 15:14:10.697861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad7385ff7f96'
down_revision = '9753a31c8deb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_grant_types',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persistent_grant_type_id'], ['persistent_grant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'persistent_grant_type_id')
    )
    op.drop_table('client_grant_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_grant_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grant_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='client_grant_types_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='client_grant_types_pkey')
    )
    op.drop_table('clients_grant_types')
    # ### end Alembic commands ###
