"""draft4

Revision ID: b4e00362a6ec
Revises: 7b75b4b943a4
Create Date: 2023-02-10 15:05:40.797607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e00362a6ec'
down_revision = '7b75b4b943a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
