"""draft4

Revision ID: b5a13fed0b3a
Revises: f7477facb073
Create Date: 2023-02-10 13:10:48.183500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a13fed0b3a'
down_revision = 'f7477facb073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
