"""draft2

Revision ID: b649b2e6ffb2
Revises: 9d5f0916522f
Create Date: 2023-02-09 16:14:34.175314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b649b2e6ffb2'
down_revision = '9d5f0916522f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('persistent_grant_type', sa.Integer(), nullable=False))
    op.drop_constraint('persistent_grants_key_key', 'persistent_grants', type_='unique')
    op.drop_constraint('persistent_grants_key_key1', 'persistent_grants', type_='unique')
    op.drop_constraint('persistent_grants_type_of_grant_fkey', 'persistent_grants', type_='foreignkey')
    op.create_foreign_key(None, 'persistent_grants', 'persistent_grant_types', ['persistent_grant_type'], ['id'], ondelete='CASCADE')
    op.drop_column('persistent_grants', 'type_of_grant')
    op.drop_column('persistent_grants', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('persistent_grants', sa.Column('type_of_grant', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.create_foreign_key('persistent_grants_type_of_grant_fkey', 'persistent_grants', 'persistent_grant_types', ['type_of_grant'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('persistent_grants_key_key1', 'persistent_grants', ['key'])
    op.create_unique_constraint('persistent_grants_key_key', 'persistent_grants', ['key'])
    op.drop_column('persistent_grants', 'persistent_grant_type')
    # ### end Alembic commands ###
