"""clients_grant_types_many_to_many

Revision ID: b7dec17bc956
Revises: f24348bff4e8
Create Date: 2023-03-23 13:40:45.922855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dec17bc956'
down_revision = 'f24348bff4e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_granttypes',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('persistent_grant_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persistent_grant_type_id'], ['persistent_grant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'persistent_grant_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_granttypes')
    # ### end Alembic commands ###
