"""checkconstraint users

Revision ID: b859cc17b241
Revises: c82aaab5c892
Create Date: 2023-02-07 18:14:35.815558

"""
from alembic import op
import sqlalchemy as sa
from src.data_access.postgresql.tables.users import USER_CLAIM_TYPE

def from_list_of_str_to_str(values):
    result = ""
    for value in values:
        result += "\'"+value+"\', "
    return result[:-2]

# revision identifiers, used by Alembic.
revision = 'b859cc17b241'
down_revision = 'c82aaab5c892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "claim_type_in_list",
        "user_claims",
        f'"claim_type" IN ({from_list_of_str_to_str(USER_CLAIM_TYPE)})'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
