"""draft3

Revision ID: b9090d63db5b
Revises: 5db1cd16fa72
Create Date: 2023-02-09 16:26:26.754252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9090d63db5b'
down_revision = '5db1cd16fa72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persistent_grants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_grants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persistent_grant_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['persistent_grant_type_id'], ['persistent_grant_types.id'], name='persistent_grants_persistent_grant_type_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='persistent_grants_pkey')
    )
    # ### end Alembic commands ###
