"""smahit

Revision ID: bc3c8fa45afa
Revises: 207968b59e47
Create Date: 2023-02-09 13:04:55.481254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3c8fa45afa'
down_revision = '207968b59e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
