"""client choices

Revision ID: bd717cc7d664
Revises: d17157d6167d
Create Date: 2023-02-08 12:14:21.846024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd717cc7d664'
down_revision = 'd17157d6167d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ACCESS_TOKEN_TYPES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('PROTOCOL_TYPES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('REFRESH_TOKEN_EXPIRATION',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('REFRESH_TOKEN_USAGE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('clients', sa.Column('access_token_type_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('protocol_type_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('refresh_token_expiration_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('refresh_token_usage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'REFRESH_TOKEN_USAGE', ['refresh_token_usage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'PROTOCOL_TYPES', ['protocol_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'REFRESH_TOKEN_EXPIRATION', ['refresh_token_expiration_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients', 'ACCESS_TOKEN_TYPES', ['access_token_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'protocol_type')
    op.drop_column('clients', 'refresh_token_usage')
    op.drop_column('clients', 'access_token_type')
    op.drop_column('clients', 'refresh_token_expiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('refresh_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('access_token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('refresh_token_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('protocol_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'refresh_token_usage_id')
    op.drop_column('clients', 'refresh_token_expiration_id')
    op.drop_column('clients', 'protocol_type_id')
    op.drop_column('clients', 'access_token_type_id')
    op.drop_table('REFRESH_TOKEN_USAGE')
    op.drop_table('REFRESH_TOKEN_EXPIRATION')
    op.drop_table('PROTOCOL_TYPES')
    op.drop_table('ACCESS_TOKEN_TYPES')
    # ### end Alembic commands ###
