"""userclaim-added-new-types

Revision ID: bebd5107d790
Revises: 804322f63370
Create Date: 2022-12-07 12:02:50.220375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebd5107d790'
down_revision = '804322f63370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
