"""checkconstraint res related

Revision ID: c82aaab5c892
Revises: 8926453f268f
Create Date: 2023-02-07 18:05:26.670640

"""
from alembic import op
import sqlalchemy as sa
from src.data_access.postgresql.tables.resources_related import API_SCOPE_CLAIM_TYPE, API_CLAIM_TYPE, API_SECRET_TYPE

def from_list_of_str_to_str(values):
    result = ""
    for value in values:
        result += "\'"+value+"\', "
    return result[:-2]

# revision identifiers, used by Alembic.
revision = 'c82aaab5c892'
down_revision = '8926453f268f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "type_in_list",
        "api_scope_claims",
        f'"type" IN ({from_list_of_str_to_str(API_SCOPE_CLAIM_TYPE)})'
    )
    op.create_check_constraint(
        "type_in_list",
        "api_claims",
        f'"type" IN ({from_list_of_str_to_str(API_CLAIM_TYPE)})'
    )
    op.create_check_constraint(
        "type_in_list",
        "api_secrets",
        f'"type" IN ({from_list_of_str_to_str(API_SECRET_TYPE)})'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
