"""access_token_type_id_update

Revision ID: c9363d376df0
Revises: fa27d2e2c4fd
Create Date: 2023-05-18 11:39:10.967510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9363d376df0'
down_revision = 'fa27d2e2c4fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_token_types', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('access_token_types', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('protocol_types', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('protocol_types', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocol_types', 'updated_at')
    op.drop_column('protocol_types', 'created_at')
    op.drop_column('access_token_types', 'updated_at')
    op.drop_column('access_token_types', 'created_at')
    # ### end Alembic commands ###
