"""smahit

Revision ID: ca5484af536a
Revises: 52d6bc49c778
Create Date: 2023-02-09 12:16:20.896578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5484af536a'
down_revision = '52d6bc49c778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_claims', 'claim_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('claim_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
