"""draft3

Revision ID: ca5d6fa00047
Revises: 06cdaa004dee
Create Date: 2023-02-09 16:32:25.145798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5d6fa00047'
down_revision = '06cdaa004dee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persistent_grant_types_type_of_grant_key', 'persistent_grant_types', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('persistent_grant_types_type_of_grant_key', 'persistent_grant_types', ['type_of_grant'])
    # ### end Alembic commands ###
