"""Devices

Revision ID: ccf9fffc92bc
Revises: 4feaa6506b2e
Create Date: 2023-02-15 17:13:06.427979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf9fffc92bc'
down_revision = '4feaa6506b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_code', sa.String(length=80), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('verification_uri', sa.String(), nullable=False),
    sa.Column('verification_uri_complete', sa.String(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code'),
    sa.UniqueConstraint('user_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
