"""userclaim choices

Revision ID: ceebcca24ed7
Revises: bd717cc7d664
Create Date: 2023-02-08 12:24:49.433281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceebcca24ed7'
down_revision = 'bd717cc7d664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER_CLAIM_TYPE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.add_column('user_claims', sa.Column('claim_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_claims', 'USER_CLAIM_TYPE', ['claim_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_claims', 'claim_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_claims', sa.Column('claim_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.drop_column('user_claims', 'claim_type_id')
    op.drop_table('USER_CLAIM_TYPE')
    # ### end Alembic commands ###
