"""add client_id to device table

Revision ID: d1ab30f42ff7
Revises: 0a847d114082
Create Date: 2023-02-07 08:47:50.995667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ab30f42ff7'
down_revision = '0a847d114082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('client_id', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'devices', ['device_code'])
    op.create_unique_constraint(None, 'devices', ['user_code'])
    op.create_foreign_key(None, 'devices', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'client_id')
    # ### end Alembic commands ###
