"""Cascade Delete for userclaims

Revision ID: d4e782d78fac
Revises: 211831e19385
Create Date: 2023-01-30 17:48:27.553203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e782d78fac'
down_revision = '211831e19385'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_claims_User_fkey', 'user_claims', type_='foreignkey')
    op.create_foreign_key(None, 'user_claims', 'users', ['User'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.create_foreign_key('user_claims_User_fkey', 'user_claims', 'users', ['User'], ['id'])
    # ### end Alembic commands ###
