"""client choices

Revision ID: d97c303861d0
Revises: 7130fa0db93f
Create Date: 2023-02-08 13:04:31.832679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97c303861d0'
down_revision = '7130fa0db93f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
