"""chenge grant subject_id to foreign key

Revision ID: dd595b33f54e
Revises: 2b4922944b7b
Create Date: 2022-12-08 07:57:06.635739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd595b33f54e'
down_revision = '2b4922944b7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persistent_grants', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'persistent_grants', 'users', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_grants', type_='foreignkey')
    op.alter_column('persistent_grants', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
