"""client_id_column_delete

Revision ID: ddb8b065c1d5
Revises: a1885569f09d
Create Date: 2023-02-10 15:40:01.699069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb8b065c1d5'
down_revision = 'a1885569f09d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_claims_client_id_fkey', 'client_claims', type_='foreignkey')
    op.drop_column('client_claims', 'client_id')
    op.drop_constraint('client_cors_origins_client_id_fkey', 'client_cors_origins', type_='foreignkey')
    op.drop_column('client_cors_origins', 'client_id')
    op.drop_constraint('client_grant_types_client_id_fkey', 'client_grant_types', type_='foreignkey')
    op.drop_column('client_grant_types', 'client_id')
    op.drop_constraint('client_id_restrictions_client_id_fkey', 'client_id_restrictions', type_='foreignkey')
    op.drop_column('client_id_restrictions', 'client_id')
    op.drop_constraint('client_post_logout_redirect_uris_client_id_fkey', 'client_post_logout_redirect_uris', type_='foreignkey')
    op.drop_column('client_post_logout_redirect_uris', 'client_id')
    op.drop_constraint('client_redirect_uris_client_id_fkey', 'client_redirect_uris', type_='foreignkey')
    op.drop_column('client_redirect_uris', 'client_id')
    op.drop_constraint('client_scopes_client_id_fkey', 'client_scopes', type_='foreignkey')
    op.drop_column('client_scopes', 'client_id')
    op.drop_constraint('client_secrets_client_id_fkey', 'client_secrets', type_='foreignkey')
    op.drop_column('client_secrets', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_secrets', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_secrets_client_id_fkey', 'client_secrets', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_scopes', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_scopes_client_id_fkey', 'client_scopes', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_redirect_uris', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_redirect_uris_client_id_fkey', 'client_redirect_uris', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_post_logout_redirect_uris', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_post_logout_redirect_uris_client_id_fkey', 'client_post_logout_redirect_uris', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_id_restrictions', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_id_restrictions_client_id_fkey', 'client_id_restrictions', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_grant_types', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_grant_types_client_id_fkey', 'client_grant_types', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_cors_origins', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_cors_origins_client_id_fkey', 'client_cors_origins', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('client_claims', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_claims_client_id_fkey', 'client_claims', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
