"""Add abstract and ChoiceType

Revision ID: dedb0efbd18d
Revises: 6a39c6b2d14b
Create Date: 2022-11-23 15:39:58.305092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedb0efbd18d'
down_revision = '6a39c6b2d14b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_claims', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_claims', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_cors_origins', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_cors_origins', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_grant_types', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_grant_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_id_restrictions', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_id_restrictions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_post_logout_redirect_uris', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_post_logout_redirect_uris', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_redirect_uris', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_redirect_uris', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_scopes', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_scopes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_secrets', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('client_secrets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('clients', 'access_token_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'protocol_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'refresh_token_expiration',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'refresh_token_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'refresh_token_usage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'refresh_token_expiration',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'protocol_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'access_token_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('client_secrets', 'updated_at')
    op.drop_column('client_secrets', 'created')
    op.drop_column('client_scopes', 'updated_at')
    op.drop_column('client_scopes', 'created')
    op.drop_column('client_redirect_uris', 'updated_at')
    op.drop_column('client_redirect_uris', 'created')
    op.drop_column('client_post_logout_redirect_uris', 'updated_at')
    op.drop_column('client_post_logout_redirect_uris', 'created')
    op.drop_column('client_id_restrictions', 'updated_at')
    op.drop_column('client_id_restrictions', 'created')
    op.drop_column('client_grant_types', 'updated_at')
    op.drop_column('client_grant_types', 'created')
    op.drop_column('client_cors_origins', 'updated_at')
    op.drop_column('client_cors_origins', 'created')
    op.drop_column('client_claims', 'updated_at')
    op.drop_column('client_claims', 'created')
    # ### end Alembic commands ###
