"""draft4

Revision ID: dfd5f636cd34
Revises: 6ab86a22919b
Create Date: 2023-02-10 12:30:45.805769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd5f636cd34'
down_revision = '6ab86a22919b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
