"""draft4

Revision ID: e28eeb6a87b1
Revises: 90a127114489
Create Date: 2023-02-10 09:25:24.009847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28eeb6a87b1'
down_revision = '90a127114489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_claims', sa.Column('claim_value', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_claims', 'claim_value')
    # ### end Alembic commands ###
