"""smahit

Revision ID: e3062c87dae0
Revises: e4fd7d20640a
Create Date: 2023-02-08 19:29:24.764183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3062c87dae0'
down_revision = 'e4fd7d20640a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_claim_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'user_claims', 'user_claim_types', ['claim_type'], ['type'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_claims', type_='foreignkey')
    op.alter_column('user_claims', 'claim_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('user_claim_types')
    # ### end Alembic commands ###
