"""add icon class to identity provider

Revision ID: e4023e1f2095
Revises: b5fab5d6a04a
Create Date: 2023-02-17 10:51:09.604936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4023e1f2095'
down_revision = 'b5fab5d6a04a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_providers', sa.Column('provider_icon', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_providers', 'provider_icon')
    # ### end Alembic commands ###
