"""draft4

Revision ID: f7477facb073
Revises: 179422e294f2
Create Date: 2023-02-10 13:09:07.874728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7477facb073'
down_revision = '179422e294f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_grants', sa.Column('data', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_grants', 'data')
    # ### end Alembic commands ###
