"""clients_token_endpoint_auth_method

Revision ID: fa27d2e2c4fd
Revises: ad7385ff7f96
Create Date: 2023-03-23 15:46:19.492384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa27d2e2c4fd'
down_revision = 'ad7385ff7f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('token_endpoint_auth_method', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'token_endpoint_auth_method')
    # ### end Alembic commands ###
