"""smahit

Revision ID: fb1f01943733
Revises: 5e08c4ad8654
Create Date: 2023-02-09 12:45:22.391071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1f01943733'
down_revision = '5e08c4ad8654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
