[default]

[default.security]
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30


[default.db]
uri = ""
port = 5432
max_connection_count = 10
echo = false


[default.redis]
scheme = "redis://"
host = "localhost"
port = 6379


[default.logging]
console_log_level = "DEBUG"
all_logs_files_path = "./logs/all/"
all_logs_filename = "all_identity_server_provider.log"
important_logs_files_path = "./logs/important/"
important_logs_filename = "important_identity_server_provider.log"

[default.server]
base_url_host = "127.0.0.1"
base_url_port = "8000"
domain_name = "rnd-identityserver-dev.godeltech.com"

[default.rsa]
rsa_key_pair = ""