name: release

on:
  # run when a release has been created
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#
#      - name: Build Docker image
#        run: docker build -t auth-server-image .

      - name: Testing
        run: echo "Release just happened"

