name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t auth-server-image .

      - name: Testing
        run: echo "Hello"

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: |
          docker run -d --name auth-server-container --network host --env ENVIRONMENT_NAME=test --env ENV_FOR_DYNACONF=test -v /var/run/docker.sock:/var/run/docker.sock auth-server-image
          docker exec -i auth-server-container sh -c "pytest --cov=src"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker
        run: |
          docker tag auth-server-image levigoldman/auth-server
          docker push levigoldman/auth-server
