name: Build and Test Auth Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t auth-server-image .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: |
          docker run -d --name auth-server-container --net=host --env ENVIRONMENT_NAME=test auth-server-image
          docker exec auth-server-container sh -c "pytest --cov=src"
