name: Build and Test Auth Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Build Docker image
#        run: docker build -t auth-server-image .

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

#      - name: Run tests
#        run: |
#          docker run -d --name auth-server-container --network host --env ENVIRONMENT_NAME=test --env ENV_FOR_DYNACONF=test -v /var/run/docker.sock:/var/run/docker.sock auth-server-image
#          docker exec -i auth-server-container sh -c "pytest --cov=src"

      - name: Push image to Amazon ECR
        run: bash deploy/deploy.sh
